baseURL : 
languageCode : en-us
title : Sodium Title
#theme : sodium

taxonomies:
  category: categories
  tag: tags

params:
  social:
    facebook: uicardio
    instagram: uicardio
    twitter: uicardio

  scripts:
    googleanalytics: 
    disqus: 
    
